-- DropForeignKey
ALTER TABLE `task` DROP FOREIGN KEY `Task_AssigneId_fkey`;

-- AlterTable
ALTER TABLE `task` MODIFY `AssigneId` INTEGER NULL,
    MODIFY `StoryPoint` VARCHAR(191) NULL,
    MODIFY `endDate` DATETIME(3) NULL,
    MODIFY `label` VARCHAR(191) NULL,
    MODIFY `startDate` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AddForeignKey
ALTER TABLE `Task` ADD CONSTRAINT `Task_AssigneId_fkey` FOREIGN KEY (`AssigneId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
